emb-net:
  - dim: 200
    dim_e: 200
    dim_t: 100
    history: 1
    layer: 1
    sample: '-1'
    granularity: 36
    r_limit: 10
gen-net:
  - dim_r: 200
    arch: 'dense-dense-dense'
    dim: '1024-1024-2048'
    att_head: '0-0-0'
    history: '31 23 15 7 3 1 0'
train:
  - fwd: 1300
    epoch: 10
    batch_size: 1024
    lr: 0.0005
    dropout: 0.3
    weight_decay: 0.00001
    norm_loss: True 
# run1:
# raw MRR:      0.1381 hit3: 0.1442 hit10: 0.2601
# filtered MRR: 0.5496 hit3: 0.5478 hit10: 0.5834
# run2:
# raw MRR:      0.1372 hit3: 0.1443 hit10: 0.2600
# filtered MRR: 0.5500 hit3: 0.5484 hit10: 0.5840
# run3:
# raw MRR:      0.1358 hit3: 0.1423 hit10: 0.2580
# filtered MRR: 0.5502 hit3: 0.5484 hit10: 0.5837