emb-net:
  - dim: 200
    dim_e: 200
    dim_t: 100
    history: 1
    layer: 1
    sample: '-1'
    granularity: 5
    r_limit: 10
gen-net:
  - dim_r: 200
    arch: 'selfatt-dense-dense'
    dim: '896-1024-2048'
    att_head: '4-0-0'
    history: '31 23 15 7 3 1 0'
train:
  - fwd: 119
    epoch: 100
    batch_size: 1024
    lr: 0.0002
    dropout: 0.4
    weight_decay: 0.00001
    norm_loss: True
# run1:
# raw MRR:      0.1981 hit3: 0.2166 hit10: 0.3599
# filtered MRR: 0.5278 hit3: 0.5292 hit10: 0.5746
# run2:
# raw MRR:      0.2000 hit3: 0.2196 hit10: 0.3593
# filtered MRR: 0.5284 hit3: 0.5296 hit10: 0.5746
# run3:
# raw MRR:      0.1980 hit3: 0.2171 hit10: 0.3594
# filtered MRR: 0.5269 hit3: 0.5278 hit10: 0.5735